{"uid":"5a9f7dfb3981363b","name":"test_sorting_by_ACS_price_advanced_search","fullName":"Tests.Steam_API.test_advanced_search_api.app_review_api_tests#test_sorting_by_ACS_price_advanced_search","historyId":"42f3a7df6660f4958a5aa1b6e881a606","time":{"start":1711446762177,"stop":1711446764916,"duration":2739},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":true,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_app_review_api_tests","time":{"start":1711446761739,"stop":1711446761739,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_app_review_api_tests::0","time":{"start":1711446764916,"stop":1711446764916,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"hasContent":false,"stepsCount":0,"attachmentStep":false,"attachmentsCount":0,"shouldDisplayMessage":false}],"labels":[{"name":"parentSuite","value":"Tests.Steam_API"},{"name":"suite","value":"test_advanced_search_api"},{"name":"subSuite","value":"app_review_api_tests"},{"name":"host","value":"fv-az836-25"},{"name":"thread","value":"7120-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Tests.Steam_API.test_advanced_search_api"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":1,"unknown":0,"total":2},"items":[{"uid":"fea3b4c7a06def00","reportUrl":"https://jameel978.github.io/Steam-Automation-Project/allure-action/main/allure-report/8433887864_1711446885993/#testresult/fea3b4c7a06def00","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPSConnectionPool(host='store.steampowered.com', port=443): Max retries exceeded with url: /api/appdetails?appids=2477000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002D7B6BEC430>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))","time":{"start":1711446513476,"stop":1711446536975,"duration":23499}}]},"tags":[]},"source":"5a9f7dfb3981363b.json","parameterValues":[]}